{
  "openapi": "3.0.0",
  "info": {
    "title": "Ms. Mary Store",
    "contact": {},
    "version": "1.0"
  },
  "servers": [
    {
      "url": "http://localhost:3000/api/v1",
      "variables": {}
    }
  ],
  "paths": {
    "/employees": {
      "post": {
        "tags": [
          "employee"
        ],
        "summary": "Create employee",
        "operationId": "Createemployee",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateemployeeRequest"
              },
              "example": {
                "name": "Zinedine Zidane",
                "cpf": "38753579062",
                "office": "gerente",
                "birthday": "19/01/1979"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      },
      "get": {
        "tags": [
          "employee"
        ],
        "summary": "Find employee",
        "operationId": "Findemployee",
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      },
      "put": {
        "tags": [
          "employee"
        ],
        "summary": "Update employee",
        "operationId": "Updateemployee",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/UpdateemployeeRequest"
              },
              "example": {
                "name": "Ronaldo Nazário",
                "office": "caixa",
                "situation": "deactivate"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      },
      "delete": {
        "tags": [
          "employee"
        ],
        "summary": "Delete employee",
        "operationId": "Deleteemployee",
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      }
    },
    "/products": {
      "post": {
        "tags": [
          "product"
        ],
        "summary": "Create product",
        "operationId": "Createproduct",
        "parameters": [],
        "requestBody": {
          "description": "",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/CreateproductRequest"
              },
              "example": {
                "name": "notebook dell",
                "category": "eletronico",
                "price": "2.90",
                "employee_id": "e13b7bab-5245-4382-83fd-a6f52be5fd4e"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      },
      "get": {
        "tags": [
          "product"
        ],
        "summary": "Find product",
        "operationId": "Findproduct",
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "deprecated": false
      }
    }
  },
  "components": {
    "schemas": {
      "CreateemployeeRequest": {
        "title": "CreateemployeeRequest",
        "required": [
          "name",
          "cpf",
          "office",
          "birthday"
        ],
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "cpf": {
            "type": "string"
          },
          "office": {
            "type": "string"
          },
          "birthday": {
            "type": "string"
          }
        },
        "example": {
          "name": "Zinedine Zidane",
          "cpf": "38753579062",
          "office": "gerente",
          "birthday": "19/01/1979"
        }
      },
      "UpdateemployeeRequest": {
        "title": "UpdateemployeeRequest",
        "required": [
          "name",
          "office",
          "situation"
        ],
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "office": {
            "type": "string"
          },
          "situation": {
            "type": "string"
          }
        },
        "example": {
          "name": "Ronaldo Nazário",
          "office": "caixa",
          "situation": "deactivate"
        }
      },
      "CreateproductRequest": {
        "title": "CreateproductRequest",
        "required": [
          "name",
          "category",
          "price",
          "employee_id"
        ],
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "category": {
            "type": "string"
          },
          "price": {
            "type": "string"
          },
          "employee_id": {
            "type": "string"
          }
        },
        "example": {
          "name": "notebook dell",
          "category": "eletronico",
          "price": "2.90",
          "employee_id": "e13b7bab-5245-4382-83fd-a6f52be5fd4e"
        }
      }
    }
  },
  "tags": [
    {
      "name": "employee"
    },
    {
      "name": "product"
    }
  ]
}